services:

  gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - links-service
      - frontend-service
      - analytics-service

  auth-service:
    build: ./auth-service
    environment:
      PORT: 3001
    expose:
      - "3001"

  links-service:
    build: ./links-service
    environment:
      PORT: "3002"
    expose:
      - "3002"
    depends_on:
      - analytics-service

  frontend-service:
    build: ./frontend-service
    environment:
      PORT: 3003
    expose:
      - "3003"

  analytics-service:
    build: ./analytics-service
    environment:
      PORT: 3004
    expose:
      - "3004"